baseURL = 'https://yourusername.github.io/your-blog-name'
languageCode = 'en-us'
title = 'Your Blog Title'
theme = 'PaperMod'

# Enable emoji support
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 5

# Enable RSS
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false


[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Your Blog Title"
  description = "A blog about technology, programming, and more!"
  keywords = ["Blog", "Portfolio", "Technology"]
  author = "Your Name"
  # images = ["<link or absolute path to image>"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    # disableHLJS = true # to disable highlight.js
    # disableFingerprinting = true
    favicon = "<link / absolute url>"
    favicon16x16 = "<link / absolute url>"
    favicon32x32 = "<link / absolute url>"
    apple_touch_icon = "<link / absolute url>"
    safari_pinned_tab = "<link / absolute url>"

  [params.label]
    text = "Your Blog"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

  # profile-mode
  [params.profileMode]
    enabled = false # needs to be explicitly set
    title = "Your Name"
    subtitle = "👋 Welcome to my blog"
    imageUrl = "<url of image>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Your Name"
    
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"

  # home-info mode
  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my blog! I write about technology, programming, DevOps, and other interesting topics."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourusername"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/yourusername"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/yourusername"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:your.email@example.com"

[params.analytics.bing]
  SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
  SiteVerificationTag = "XYZabc"

[[params.fuseOpts]]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = "github"

[outputs]
  home = ["HTML", "RSS", "JSON"] # is necessary
